!FINDING THE ROOT OF A EQUATION BY BISECTION METHOD
PROGRAM BISECTION_METHOD
 IMPLICIT NONE
 INTEGER::I,J
 REAL::F,X1,X2,ROOT,TEMP
 PRINT*,"ENTER FIRST BOUNDERY VALUE OF A ROOT"
  READ*,X1
 PRINT*,"ENTER SECOND BOUNDERY VALUE OF THE ROOT"
  READ*,X2
DO I=1,100
IF(F(X1)*F(X2) < 0)THEN
  TEMP=(X1+X2)/2
  IF(F(X1)*F(TEMP) < 0 )THEN
    X2=TEMP
  ELSEIF(F(X2)*F(TEMP) < 0) THEN
    X1=TEMP
  ENDIF
  
ELSE
 PRINT*,"NO ROOT AVAILABLE IN BETWEEN THIS BOUNDERY VALUE"
END IF
END DO
ROOT=X2
PRINT*,"ROOT=",ROOT
END PROGRAM BISECTION_METHOD

REAL FUNCTION F(X)
 IMPLICIT NONE
 REAL,INTENT(IN)::X
 F=X*TAN(X) - 1.28
END FUNCTION F
